= System Structure

== Plugin Manager (PM) System consists of three parts:

=== 1. Plugin Manager Code - inside OpenCPN

Purpose: This code handles all operations under **Options > Plugins** and the PI User Interface.

=== 2. Plugin Code - CMake & CI added via Templates

Purpose: Provide a prebuilt and tested CMake Template to enable Continuous Integration (CI) to manage the routine tasks required to build and deploy multiple build environments.

xref:pm-tp-system-structure.adoc[CI-CMake Template] has more detail for these steps:

. Confirm the plugin builds locally and works properly before starting.
. Step by step Instructions
. List of folders and files needed
. Process to make a backup and to apply the folders and files to the plugin.


=== 3. Transfer of metadata files to Catalog Library

Purpose:

. To collect all the plugins metadata.xml's for the various environments and push them to opencpn/plugins master branch.
. The metadate.xml file contains all necessary PI information and location of tarball files so that these files can be accessed and downloaded to OpenCPN catalog to be used to download the associated tarball when the user chooses.
. Refer to https://github.com/OpenCPN/plugins/blob/master/DEVELOPER-INFO.md[OpenCPN plugins project README]


==== Plugin Developer actions:

. Uses script to copy metadata.xml files from Cloudsmith to Github.com/opencpn/plugins.
. Removes older plugin release if present.
. Git add the new files.
. Git commit to remote
. Makes a Pull Request (PR) to github.com/opencpn/plugins master branch.
. Confirms that the github action script accepts the PR.

==== Library Maintainer Dave reviews Pull Request:

. Accepts or rejects the PR.
. If the PR is accepted, the metadata.xml files are added to the Catalog Library
. Users can then use the "Update Plugin Catalog" button in Options > Plugins to update the catalog.

==== Catalog now available to the User in **Options > Plugins**

The excellent Graphic on this page describes the system structure as xref:pm-overview-deployment.adoc[Deployment Overview Graphic].
