= Antora Developer Manual demo

This is a quick try to understand how Antora + asciidoc could be used 
to maintain the Developer manual. It is a quick shot, long way from completed.
That said, my personal impression is that shows how Antora's 
capabilities fits our needs very well

* The manual as such lives as simple ascii files in a git repo. This is a
  well-known environment for developers, and submitting patches and PRs
  is simple.

* This manual is actually linked to other manuals: the opencpn/leamas/wiki
  plugin installer docs and the shipdriver manual. These are separate git
  repos which could (and should) be maintained by other people than the
  main manual. See for example how elegant the plugin manual is integrated
  in the main manual.

An occasionally updated demo is available at http://mumin.crabdance.com/site

Note the link to the plugin, bottom left in navigation frame.

The complete manual is easily rebuilt using this playbook:

```
site:
  title: OpenCPN Developer Manual
  url: http://mumin.crabdance.com/site
  start_page: ocpn-dev-manual::developer_guide.adoc

content:
  sources:
    - url: https://github.com/leamas/ocpn-dev-manual.git
      branches: main   
      edit_url: false
    - url:  https://github.com/leamas/shipdriver_pi.git
      branches: master   
      edit_url: true
    - url: https://github.com/leamas/ocpn-pi-docs.git
      branches: main   
      edit_url: false

ui:   
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
```

